---
- name: Ensure deploy user exists
  user:
    name: deploy

- name: Create gpii-ci-ssh/
  file:
    path: /home/deploy/gpii-ci-ssh
    state: directory
    owner: deploy
    group: adm
    mode: 0700

- name: Configure gpii-ci-ssh/known_hosts
  copy:
    src: files/ssh_known_hosts
    dest: /home/deploy/gpii-ci-ssh/known_hosts
    owner: deploy
    group: adm
    mode: 0644
    backup: yes

- name: Configure gcr_uploader_creds.json
  copy:
    content: "{{ gpii_version_updater_gcr_uploader_creds | mandatory }}"
    dest: /home/deploy/gcr_uploader_creds.json
    owner: deploy
    group: adm
    mode: 0700

- name: Force pull version-updater image
  docker_image:
    name: gpii/version-updater:latest
    force: yes

- name: Run version-updater container
  docker_container:
    name: version-updater
    image: gpii/version-updater:latest
    state: started
    restart: yes
    restart_policy: always
    volumes:
      - /home/deploy/gpii-ci-ssh:/home/app/.ssh:ro,Z
