---
- name: Ensure deploy user exists
  user:
    name: deploy

- name: Create gpii-ci-ssh/
  file:
    path: /home/deploy/gpii-ci-ssh
    state: directory
    owner: deploy
    group: deploy
    mode: 0700

- name: Configure gpii-ci-ssh/known_hosts
  copy:
    src: files/ssh_known_hosts
    dest: /home/deploy/gpii-ci-ssh/known_hosts
    owner: deploy
    group: deploy
    mode: 0644
    backup: yes

- name: Configure gpii-ci-ssh/config
  copy:
    src: files/ssh_config
    dest: /home/deploy/gpii-ci-ssh/config
    owner: deploy
    group: deploy
    mode: 0644
