---
- name: Create gpii-ci-ssh/
  file:
    path: /root/gpii-ci-ssh
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Configure gpii-ci-ssh/known_hosts
  copy:
    src: files/ssh_known_hosts
    dest: /root/gpii-ci-ssh/known_hosts
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Force pull version-updater image
  docker_image:
    name: gpii/version-updater:latest
    force: yes

- name: Run version-updater container
  docker_container:
    name: version-updater
    image: gpii/version-updater:latest
    state: started
    restart: yes
    restart_policy: always
    volumes:
      - /root/gpii-ci-ssh/id_rsa.gpii-ci:/root/.ssh/id_rsa.gpii-ci:ro,Z
      - /root/gpii-ci-ssh/known_hosts:/root/.ssh/known_hosts:ro,Z
